### PR TITLE
Feature/skip night

### PR DESCRIPTION
**Pull request by nomadjimbob**
Added the ability to skip the night in survival

### CODE REVIEW

**Comment by ProjectHSI** [comment]
probably a bit late, but while this does add smooth night transitions i feel like bumping `randomTickRate` or the tick rate in general is at-least a bit warranted here.

**Comment by nomadjimbob** [comment]
Is it possible to do that and only affect a single world and not the whole server?

**Comment by ProjectHSI** [comment]
> Is it possible to do that and only affect a single world and not the whole server?

not sure about bukkit but it might be possible with PaperMC Folia through it's expansion into dedicated region schedulers although i'm pretty sure we all know that most plugins aren't compatible with it

**Comment by ProjectHSI** [comment]
`randomTickSpeed` is possible as MultiVerse implements it, not sure about tick rate though.

**Comment by nomadjimbob** [comment]
We use [MyWorlds](https://wiki.traincarts.net/p/MyWorlds) for world management and it doesn't look like it supports it. If we were to implement it, it would need to be added in to the STEMCraft plugin directly. We do need to also add in a Nether ratio which Multiverse Nether has implemented in the future as well, so it might be good to add both into the next version

**Comment by nomadjimbob** [comment]
randomTickSpeed is now set by default to 300 while skipping

**Pull request merged**
