### PR TITLE
feature/gh-issue-forms merge

### PR DESCRIPTION
**Pull request by ProjectHSI**
adds issue templates for issue filing

### CODE REVIEW

**Comment by nomadjimbob** [comment]
I think it would be better if the proxy was merged into the bug/feature. A field could be added to the form on who was reporting this if not the author of the issue as bugs/features could also come from workshops, email, etc.

I have also updated the tags (sorry), so they will need to be update in the templates.

**Comment by ProjectHSI** [comment]
I think it'd be better if the workshops, email, and tickets were merged into 2 proxies.
That way, we hide the details of the proxy, showing only what the user needs, and we still merge and account for all of the other things.

**Comment by nomadjimbob** [comment]
Having a 'bug' and 'proxy bug' will just confuse people. Most would not know what 'proxy bug' means. There is no need to hide details in a report, they can be marked optional and discussed if needed later in the issue. All it does is add duplication of forms.

Really, the proxy only needs to contain an author type text box of who and where. They are not important pieces of info unless you are trying to get more context of the problem/feature (and in this case it shouldn't really be created yet in GitHub if the conversation is elsewhere).

The forms already contain similar fields, for example in feature request, there is the field 'What is it that currently happens in STEMCraft?' which is marked as required. If it is a new feature, then nothing happens (so being required here is just annoying as you would have to type 'nothing doesn't exit') so I don't see it as a problem.

We need to remember that this area is being used to introduce people to Git and Coding so terminology and standards that experienced developers are accustomed to are foreign to these new people, so things need to be in simple terms and steps (I know I am not the best at this either, hence a fair bit of time this week is devoted to JavaDocs and Wiki updates)

**Comment by ProjectHSI** [comment]
ok.

**Comment by ProjectHSI** [comment]
not actively working on this, may reopen

**Pull request closed without merging**
