### PR TITLE
Hotfix/mc-depend-fix

### LINKED ISSUE #35: API Version Outdated
_api-version_ in _plugin.yml_ is set to target _1.19.x_ and _Spigot-API_ in _pom.xml_ is set to target _1.19.x_.

Since we're targeting _1.20.x_, I recommend we switch these two to target _1.20.x_.

### PR DESCRIPTION
**Pull request by ProjectHSI**

### CODE REVIEW

**Comment by nomadjimbob** [comment]
Needs to be merged into release/1.1.0 instead of main as that is currently the next release candidate. Once 1.1.0 is considered stable, then it will be merged into main and tagged (and created as an official release)

**Comment by ProjectHSI** [comment]
> Needs to be merged into release/1.1.0 instead of main as that is currently the next release candidate. Once 1.1.0 is considered stable, then it will be merged into main and tagged (and created as an official release)

Hm... Great.
GitHub doesn't automatically sync branches, my fork was created before the branches were created.
I think have to manually force Git to sync the branches. Neither the GitHub CLI nor website seem to support naturally doing this.

This can be voided if you can change the branch on this PR to the *release/1.1.0* branch.

**Comment by nomadjimbob** [comment]
Merged. Thank you

**Comment by ProjectHSI** [comment]
you're welcome

**Comment by nomadjimbob** [comment]
I am pretty confident that 1.1.0 is now stable. I will move it to release in the next hour or so and put it into production. Develop has been bumped to 1.2.0, with any bugfixes to 1.1.0 needing to be a new release of 1.1.1

**Comment by ProjectHSI** [comment]
🫠
Screenshot 2023-11-08 080329

**Comment by ProjectHSI** [comment]
finally
now all of the branches are in there

**Pull request merged**
